name: motifer
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python
    - scipy
    - scikit-learn
    - R
    - pip
    - numpy
    - numba
    - ipython
    - matplotlib
    - bioconductor-dnashaper
    - r-glmnet
    - jupyter
    - rpy2
    - seaborn
    - cython
