[workspace]

members = [
    "motifer",
    "optim",
    "infer_motifs",
    "filter_motifs",
    "evaluate_motifs",
    "get_robustness",
    #"merge_folds",
    #"ShapeIT",
    #"locate_motifs",
]

