name: motifer
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python
    - scikit-learn
    - R
    - pip
    - numpy
    - numba
    - ipython
    - matplotlib
    - bioconductor-dnashaper
    - bioconductor-genomeinfodbdata
    - bioconductor-genomeinfodb
    - r-prroc
    - r-glmnet
    - r-nnet
    - r-bh
    - boost
    - jupyter
    - rpy2
    - seaborn
    - meme
