name: motifer
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python
    - scikit-learn
    - R
    - numpy
      #- numba
      #- ipython
    - matplotlib
    - bioconductor-dnashaper
    - bioconductor-genomeinfodbdata
    - bioconductor-genomeinfodb
    - r-prroc
    - r-glmnet
      #- r-nnet
    - r-bh
      #- boost
      #- jupyter
    - rpy2
    - seaborn
    - meme
    - pip
    - sqlite
    - pip:
        - jinja2
