[default]
limits.data-form = "2MiB"
template_dir = "templates/"

[default.databases]
shapeme = { url = "db/shapeme.sqlite", timeout = 10 }

[debug]
secret_key = "HanbnePLXcmfgpwtDEpBWAKmbMvlaLTxu1yG/vGYnO4="

[release]
secret_key = "fLqw9DAvcrfmb6tB38WT5y68sutuiwHaPQ+v3/R2iVM="
